const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
const PRODUCT_DESELECTED = 'PRODUCT_DESELECTED';
const PRODUCT_PRESET = 'PRODUCT_PRESET';

export default {PRODUCT_SELECTED, PRODUCT_DESELECTED, PRODUCT_PRESET};